#!/usr/bin/env node

// scripts/setup.js
// Script para configurar o projeto automaticamente

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  blue: '\x1b[34m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

function generateSecret() {
  const crypto = require('crypto');
  return crypto.randomBytes(32).toString('base64');
}

async function setup() {
  log('\n🚀 DevBase Template Setup', 'blue');
  log('================================\n', 'blue');

  // 1. App Name
  const appName = await question('📦 App Name (default: DevBase Template): ');
  const finalAppName = appName || 'DevBase Template';

  // 2. Database
  log('\n🗄️  Database Setup', 'yellow');
  const dbChoice = await question('Use MongoDB Atlas? (y/n, default: local): ');
  let mongoUri = 'mongodb://localhost:27017/devbase-template';
  
  if (dbChoice.toLowerCase() === 'y') {
    mongoUri = await question('Enter MongoDB Atlas URI: ');
  }

  // 3. OAuth
  log('\n🔑 OAuth Setup (optional - press Enter to skip)', 'yellow');
  const githubId = await question('GitHub Client ID: ');
  const githubSecret = githubId ? await question('GitHub Client Secret: ') : '';
  
  const googleId = await question('Google Client ID: ');
  const googleSecret = googleId ? await question('Google Client Secret: ') : '';

  // 4. Cloudinary
  log('\n☁️  Cloudinary Setup (optional - press Enter to skip)', 'yellow');
  const cloudName = await question('Cloudinary Cloud Name: ');
  const cloudKey = cloudName ? await question('Cloudinary API Key: ') : '';
  const cloudSecret = cloudName ? await question('Cloudinary API Secret: ') : '';

  // Generate .env.local
  const nextAuthSecret = generateSecret();
  
  const envContent = `# Auto-generated by setup script
NEXT_PUBLIC_APP_NAME="${finalAppName}"
NEXT_PUBLIC_APP_URL="http://localhost:3000"

NEXTAUTH_SECRET="${nextAuthSecret}"
NEXTAUTH_URL="http://localhost:3000"

MONGODB_URI="${mongoUri}"

${githubId ? `GITHUB_ID="${githubId}"` : '# GITHUB_ID=""'}
${githubSecret ? `GITHUB_SECRET="${githubSecret}"` : '# GITHUB_SECRET=""'}

${googleId ? `GOOGLE_CLIENT_ID="${googleId}"` : '# GOOGLE_CLIENT_ID=""'}
${googleSecret ? `GOOGLE_CLIENT_SECRET="${googleSecret}"` : '# GOOGLE_CLIENT_SECRET=""'}

${cloudName ? `CLOUDINARY_CLOUD_NAME="${cloudName}"` : '# CLOUDINARY_CLOUD_NAME=""'}
${cloudKey ? `CLOUDINARY_API_KEY="${cloudKey}"` : '# CLOUDINARY_API_KEY=""'}
${cloudSecret ? `CLOUDINARY_API_SECRET="${cloudSecret}"` : '# CLOUDINARY_API_SECRET=""'}

NODE_ENV="development"
`;

  fs.writeFileSync('.env.local', envContent);
  log('\n✅ .env.local created!', 'green');

  // Update package.json
  const packagePath = path.join(process.cwd(), 'package.json');
  const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
  packageJson.name = finalAppName.toLowerCase().replace(/\s+/g, '-');
  fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
  log('✅ package.json updated!', 'green');

  // Update app.config.js
  const configPath = path.join(process.cwd(), 'config', 'app.config.js');
  if (fs.existsSync(configPath)) {
    let configContent = fs.readFileSync(configPath, 'utf8');
    configContent = configContent.replace(
      /name: ".*"/,
      `name: "${finalAppName}"`
    );
    fs.writeFileSync(configPath, configContent);
    log('✅ app.config.js updated!', 'green');
  }

  log('\n🎉 Setup complete!', 'green');
  log('\n📝 Next steps:', 'blue');
  log('1. npm install (if not done yet)');
  log('2. npm run dev');
  log('3. Open http://localhost:3000\n');

  rl.close();
}

setup().catch(error => {
  log(`\n❌ Error: ${error.message}`, 'red');
  rl.close();
  process.exit(1);
});