import {
  Play,
  Pause,
  RotateCcw,
  Plus,
  Sparkle,
  X,
  Coffee,
  Brain,
  Battery,
  Zap,
  Frown,
  Smile,
  SkipForward,
  LogIn,
  Check,
  Trash2,
  Briefcase,
  Dumbbell,
  Heart,
  BookOpen,
  Home,
  Pin,
  Sparkles,
  Target,
  Wind,
  Lock,
  ListTodo,
  Settings,
} from "lucide-react";



export const MOODS = {
  CREATIVE: {
    id: "creative",
    label: "Criativo",
    focusTime: 25,
    breakTime: 5,
    gradient: "linear-gradient(135deg, #a855f7 0%, #ec4899 100%)",
    icon: Brain,
    focusMessages: [
      "Deixe as ideias fluírem!",
      "Sua criatividade está no auge!",
      "Momento perfeito para inovar!",
    ],
    breakMessages: [
      "Beba água e deixe sua mente vagar",
      "Alongue os ombros e respire fundo",
      "Olhe para longe e relaxe os olhos",
    ],
  },
  UNMOTIVATED: {
    id: "unmotivated",
    label: "Desmotivado",
    focusTime: 15,
    breakTime: 5,
    gradient: "linear-gradient(135deg, #64748b 0%, #475569 100%)",
    icon: Frown,
    focusMessages: [
      "Você consegue! Um passo de cada vez",
      "Pequenos progressos ainda são progressos",
      "Seja gentil consigo mesmo hoje",
    ],
    breakMessages: [
      "Respire fundo 3 vezes e beba água",
      "Levante e caminhe um pouco",
      "Alongue o corpo todo devagar",
    ],
  },
  STRESSED: {
    id: "stressed",
    label: "Estressado",
    focusTime: 20,
    breakTime: 7,
    gradient: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    icon: Zap,
    focusMessages: [
      "Respire fundo. Você está indo bem",
      "Um passo de cada vez. Sem pressa",
      "Foco no presente, não no resultado",
    ],
    breakMessages: [
      "RESPIRE: 4 segundos dentro, 4 fora",
      "Beba água gelada devagar",
      "Alongue pescoço e ombros",
    ],
  },
  FOCUSED: {
    id: "focused",
    label: "Focado",
    focusTime: 30,
    breakTime: 5,
    gradient: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
    icon: Smile,
    focusMessages: [
      "Foco impecável! Continue assim",
      "Você está no flow perfeito",
      "Mantenha esse ritmo incrível!",
    ],
    breakMessages: [
      "Olhe para longe por 20 segundos",
      "Beba água e hidrate-se",
      "Levante e movimente as pernas",
    ],
  },
  TIRED: {
    id: "tired",
    label: "Cansado",
    focusTime: 15,
    breakTime: 10,
    gradient: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
    icon: Coffee,
    focusMessages: [
      "Devagar e sempre. Você consegue",
      "Está tudo bem ir no seu ritmo",
      "Faça o que puder por agora",
    ],
    breakMessages: [
      "Beba água ou café",
      "Considere um cochilo de 5min",
      "Alongue todo o corpo",
    ],
  },
  ENERGIZED: {
    id: "energized",
    label: "Energizado",
    focusTime: 35,
    breakTime: 5,
    gradient: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    icon: Battery,
    focusMessages: [
      "Energia máxima! Você está voando!",
      "Incrível! Mantenha esse ritmo",
      "Aproveite esse pico de produtividade",
    ],
    breakMessages: [
      "Beba água para manter a energia",
      "Alongamento rápido de 30 segundos",
      "Olhe pela janela e respire",
    ],
  },
  CUSTOM: {
    id: "custom",
    label: "Autêntico",
    focusTime: 25,
    breakTime: 5,
    gradient: "linear-gradient(135deg, #312e81 0%, #9333ea 100%)",
    icon: Sparkle,
    focusMessages: [
      "Nem sempre com vontade, mas sempre capaz.",
      "Hoje é no modo 'faço porque preciso'.",
      "Tá difícil, mas o difícil também conta.",
    ],
    breakMessages: [
      "Respira. Reclamar também é uma forma de processar.",
      "Dá um tempo, ninguém é produtivo o tempo todo.",
      "Olha pro teto por uns segundos, vai te fazer bem.",
    ],
  },
};


export const TASK_CATEGORIES = {
  trabalho: {
    id: "trabalho",
    label: "Trabalho",
    Icon: Briefcase,
    color: "#3b82f6",
  },
  "saude-fisica": {
    id: "saude-fisica",
    label: "Saúde Física",
    Icon: Dumbbell,
    color: "#10b981",
  },
  "saude-mental": {
    id: "saude-mental",
    label: "Saúde Mental",
    Icon: Heart,
    color: "#a855f7",
  },
  estudo: {
    id: "estudo",
    label: "Estudo",
    Icon: BookOpen,
    color: "#f59e0b",
  },
  pessoal: {
    id: "pessoal",
    label: "Pessoal",
    Icon: Home,
    color: "#ec4899",
  },
  outros: {
    id: "outros",
    label: "Outros",
    Icon: Pin,
    color: "#6b7280",
  },
};
